# permissions for end users to view requests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: request-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: internal-services-controller
    app.kubernetes.io/part-of: internal-services-controller
    app.kubernetes.io/managed-by: kustomize
  name: request-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - requests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - requests/status
  verbs:
  - get
