# Set the reference to the latest APIRresourceSchema
---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: internal-services-controller.appstudio.redhat.com
spec:
  latestResourceSchemas:
     - today.requests.appstudio.redhat.com

